# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GPMGridRasterReader
                                 A QGIS plugin
 Read gridded data of GPM (L3 reguarly gridded)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-14
        copyright            : (C) 2023 by GES DISC & George Mason University
        email                : gyu@gmu.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GPMGridRasterReader class from file GPMGridRasterReader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gpm_grid_data_reader import GPMGridRasterReader
    return GPMGridRasterReader(iface)
